name: Build and Push Docker java image to Docker Hub

on:
  push:
    branches:
    - main

jobs:
  push_to_registry:
    name: Push Docker java image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Checking out code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build ./docker_image_java/ --file ./docker_image_java/Dockerfile --tag javaimage:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: docker_image_java/
        push: true
        tags: docker.io/sravanimandela/build-push-action:latest

